apiVersion: apps/v1
kind: Deployment
metadata: 
  name: posts-depl
spec: 
  replicas: 1
  selector: 
    matchLabels:
      app: posts
  template:
    matadata:
      labels:
        app: posts 
    spec:
      containers: 
        - name: posts
          image: bloggy/posts:0.0.1